import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("contactus", "routes/contactus.tsx"),
  route("london", "routes/london.tsx"), // <--- Added this line
  route("switzerland", "routes/switzerland.tsx"),
  route("france", "routes/france.tsx"),
  route("italy", "routes/italy.tsx"),
  route("maldives", "routes/maldives.tsx"),
  route("indonesia", "routes/indonesia.tsx"),
  route("thailand", "routes/thailand.tsx"),
  route("vietnam", "routes/vietnam.tsx"),
  route("uae", "routes/uae.tsx"),
  route("singapore", "routes/singapore.tsx"),
  route("japan", "routes/japan.tsx"),
  route("australia", "routes/australia.tsx"),
  route("privacypolicy", "routes/privacypolicy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("kashmir", "routes/kashmir.tsx"),
  route("kerala", "routes/kerala.tsx"),
  route("andaman", "routes/andaman.tsx"),
  route("ladakh", "routes/ladakh.tsx"),
  route("goa", "routes/goa.tsx"),
  route("rajasthan", "routes/rajasthan.tsx"),
  route("gujarat", "routes/gujarat.tsx"),
  route("mp", "routes/mp.tsx"),
  route("up", "routes/up.tsx"),
  route("himachal", "routes/himachal.tsx"),
  route("meghalaya", "routes/meghalaya.tsx"),
  route("sikkim", "routes/sikkim.tsx"),
] satisfies RouteConfig;
